dtbase: HW2.cpp.o
	g++ -o dtbase HW2.o -L/usr/local/lib/mysql -lmysqlclient -lnsl -lm -I/usr/include/mysql
1627868HW2.cpp.o: HW2.cpp
	g++ -c  HW2.cpp -L/usr/local/lib/mysql  -lnsl -lmysqlclient -lm -I/usr/include/mysql 
